# Generated by Django 4.2.9 on 2026-05-06 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('country', models.CharField(choices=[('BR', 'Brasil'), ('US', 'Estados Unidos')], max_length=2)),
                ('scraper_class', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_cron', models.CharField(default='0 6 * * *', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'scraping_sources',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('country', models.CharField(choices=[('BR', 'Brasil'), ('US', 'Estados Unidos')], max_length=2)),
                ('state_province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('auction_type', models.CharField(choices=[('judicial', 'Judicial'), ('extrajudicial', 'Extrajudicial'), ('foreclosure', 'Foreclosure'), ('tax_lien', 'Tax Lien'), ('tax_deed', 'Tax Deed')], max_length=50)),
                ('auction_date', models.DateTimeField(blank=True, null=True)),
                ('auction_number', models.CharField(blank=True, max_length=255)),
                ('process_number', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('appraised_value_cents', models.BigIntegerField(blank=True, null=True)),
                ('minimum_bid_cents', models.BigIntegerField(blank=True, null=True)),
                ('market_value_cents', models.BigIntegerField(blank=True, null=True)),
                ('debt_type', models.CharField(blank=True, choices=[('iptu', 'IPTU'), ('condominium', 'Condomínio'), ('mortgage', 'Hipoteca/Financiamento'), ('property_tax', 'Property Tax'), ('hoa', 'HOA'), ('other', 'Outro')], max_length=50)),
                ('total_debt_cents', models.BigIntegerField(blank=True, null=True)),
                ('debt_details', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('discovered', 'Descoberto'), ('analyzing', 'Em Análise'), ('opportunity', 'Oportunidade'), ('discarded', 'Descartado'), ('acquired', 'Adquirido')], default='discovered', max_length=50)),
                ('estimated_profit_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roi_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('pdf_url', models.URLField(blank=True, max_length=2000)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdfs/%Y/%m/')),
                ('pdf_extracted_text', models.TextField(blank=True)),
                ('pdf_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.scrapingsource')),
            ],
            options={
                'db_table': 'properties',
                'indexes': [models.Index(fields=['country', 'state_province', 'city'], name='properties_country_6c6bac_idx'), models.Index(fields=['auction_type', 'auction_date'], name='properties_auction_90d26c_idx'), models.Index(fields=['status', 'roi_score'], name='properties_status_eabe58_idx'), models.Index(fields=['currency', 'minimum_bid_cents'], name='properties_currenc_517a48_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
