# Generated by Django 4.2.9 on 2026-06-03 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsource',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio para fonte compartilhada (visível a todos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
